# -*- coding: utf-8 -*-
"""ESPN Ranking .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XarCTJKJtllRvgtZv1fxztVXty-D_XZg
"""

import requests
import pandas as pd


url = "http://site.api.espn.com/apis/site/v2/sports/football/college-football/rankings"


response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    print(data.keys())
else:
    print(f"❌：{response.status_code}")

rankings = data["rankings"]
print(type(rankings))
print(len(rankings))
print(rankings[0].keys())

print(rankings[0]["name"])
print(rankings[0]["shortName"])
print(rankings[0]["date"])
print(len(rankings[0]["ranks"]))

for r in rankings:
    print(f"{r['id']}: {r['name']} ({r['shortName']}) - {r['date']}")

ap_top25 = next((r for r in rankings if "AP" in r["shortName"]), None)

teams = []
for t in ap_top25["ranks"]:
    teams.append({
        "rank": t["current"],
        "team": t["team"].get("location", t["team"].get("name")), # Use location or name instead of displayName
        "record": t["recordSummary"],
        "points": t["points"],
        "firstPlaceVotes": t.get("firstPlaceVotes", 0)
    })

df = pd.DataFrame(teams)
print(df.head())

import requests
import pandas as pd
from datetime import datetime

# === 1️⃣ 取得 ESPN API 資料 ===
url = "http://site.api.espn.com/apis/site/v2/sports/football/college-football/rankings"
response = requests.get(url)
data = response.json()

latest_season = data.get("latestSeason", {})
latest_week = data.get("latestWeek", {})

# === 2️⃣ 設定要擷取的榜單 ===
polls_to_extract = {
    "AP": "AP Top 25",
    "Coaches": "Coaches"
}

poll_dfs = {}

# === 3️⃣ 迴圈擷取榜單 ===
for key, name in polls_to_extract.items():
    poll_data = next((r for r in data["rankings"] if name.lower() in r["name"].lower()), None)

    if poll_data:
        teams = []
        for t in poll_data["ranks"]:
            # 轉換日期為可讀格式（例如 2025-10-12）
            poll_date = poll_data["date"]
            poll_date = datetime.strptime(poll_date, "%Y-%m-%dT%H:%MZ").strftime("%Y-%m-%d")

            teams.append({
                "season_year": latest_season.get("year", "N/A"),
                "week_number": latest_week.get("number", "N/A"),
                "poll_name": poll_data["shortName"],
                "poll_date": poll_date,
                "rank": t["current"],
                "team": t["team"].get("displayName", t["team"].get("location", t["team"].get("name"))),
                "record": t.get("recordSummary", ""),
                "points": t.get("points", ""),
                "firstPlaceVotes": t.get("firstPlaceVotes", 0)
            })

        df = pd.DataFrame(teams)
        poll_dfs[key] = df
        print(f"✅ {key} poll 加入可讀時間欄位完成，共 {len(df)} 支球隊")
    else:
        print(f"⚠️ can't find {name} ranking data")


for k, df in poll_dfs.items():
    print(f"\n🏈 {k} Poll Top 10：")
    print(df.head())